
package WenetONNX_h;
use strict; use Cwd 'realpath';  use File::Basename;  use lib dirname(__FILE__);  use SPL::Operator::Instance::OperatorInstance; use SPL::Operator::Instance::Annotation; use SPL::Operator::Instance::Context; use SPL::Operator::Instance::Expression; use SPL::Operator::Instance::ExpressionTree; use SPL::Operator::Instance::ExpressionTreeEvaluator; use SPL::Operator::Instance::ExpressionTreeVisitor; use SPL::Operator::Instance::ExpressionTreeCppGenVisitor; use SPL::Operator::Instance::InputAttribute; use SPL::Operator::Instance::InputPort; use SPL::Operator::Instance::OutputAttribute; use SPL::Operator::Instance::OutputPort; use SPL::Operator::Instance::Parameter; use SPL::Operator::Instance::StateVariable; use SPL::Operator::Instance::TupleValue; use SPL::Operator::Instance::Window; 
sub main::generate($$) {
   my ($xml, $signature) = @_;  
   print "// $$signature\n";
   my $model = SPL::Operator::Instance::OperatorInstance->new($$xml);
   unshift @INC, dirname ($model->getContext()->getOperatorDirectory()) . "/../impl/nl/include";
   $SPL::CodeGenHelper::verboseMode = $model->getContext()->isVerboseModeOn();
   print '/*', "\n";
   print ' * WenetONNX operator header', "\n";
   print ' */', "\n";
   print "\n";
   print '#ifndef WENET_ONNX_OPERATOR_H', "\n";
   print '#define WENET_ONNX_OPERATOR_H', "\n";
   print "\n";
   print '#include <SPL/Runtime/Operator/Operator.h>', "\n";
   print '#include <SPL/Runtime/Operator/ParameterValue.h>', "\n";
   print '#include <SPL/Runtime/Operator/OperatorContext.h>', "\n";
   print '#include <SPL/Runtime/Operator/Port/AutoPortMutex.h>', "\n";
   print '#include <SPL/Runtime/Operator/State/StateHandler.h>', "\n";
   print '#include <SPL/Runtime/ProcessingElement/PE.h>', "\n";
   print '#include "../../impl/include/WenetONNXImpl.hpp"', "\n";
   print '#include <memory>', "\n";
   print "\n";
   SPL::CodeGen::headerPrologue($model);
   print "\n";
   print "\n";
   print 'namespace wenet_onnx_operator {', "\n";
   print "\n";
   print 'class MY_OPERATOR : public MY_BASE_OPERATOR {', "\n";
   print 'public:', "\n";
   print '    MY_OPERATOR();', "\n";
   print '    virtual ~MY_OPERATOR();', "\n";
   print '    ', "\n";
   print '    // Process incoming tuples', "\n";
   print '    void process(Tuple const & tuple, uint32_t port);', "\n";
   print '    void process(Punctuation const & punct, uint32_t port);', "\n";
   print '    ', "\n";
   print 'private:', "\n";
   print '    // Configuration', "\n";
   print '    wenet_streams::WenetONNXImpl::Config config_;', "\n";
   print '    ', "\n";
   print '    // ONNX-based implementation', "\n";
   print '    std::unique_ptr<wenet_streams::WenetONNXImpl> wenet_impl_;', "\n";
   print '    ', "\n";
   print '    // State tracking', "\n";
   print '    bool initialized_;', "\n";
   print '    uint64_t audio_timestamp_ms_;', "\n";
   print '    uint64_t total_samples_processed_;', "\n";
   print '    ', "\n";
   print '    // Helper methods', "\n";
   print '    void initialize();', "\n";
   print '    void processAudioData(const SPL::blob& audio_blob);', "\n";
   print '    void submitResult(const wenet_streams::WenetONNXImpl::TranscriptionResult& result);', "\n";
   print '};', "\n";
   print "\n";
   print '} // namespace wenet_onnx_operator', "\n";
   print "\n";
   SPL::CodeGen::headerEpilogue($model);
   print "\n";
   print "\n";
   print '#endif // WENET_ONNX_OPERATOR_H', "\n";
   CORE::exit $SPL::CodeGen::USER_ERROR if ($SPL::CodeGen::sawError);
}
1;
